apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

story/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.db.models import Q

# class PostManager(models.Manager):
#     def search(self, query=None):
#         qs = self.get_queryset()
#         if query is not None:
#             or_lookup = (Q(title__icontains=query) | 
#                          Q(overview__icontains=query)
#                         )
#             qs = qs.filter(or_lookup).distinct() 
#             # distinct() is often necessary with Q lookups
#         return qs

class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField()
    detail = models.TextField(max_length=100)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)
    thumbnail = models.ImageField()
    detail = models.TextField()
    featured = models.BooleanField(default=True)
 
    # post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True)

    # class Meta:
    #     verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.title
    # def get_absolute_url(self):
    #     return reverse('post-category', args=[self.title])
    def get_absolute_url(self):
        return reverse('post-category', kwargs={
            'pk': self.pk
        })

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    thumbnail = models.ImageField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    # def __str__(self):
    #     return str(self.thumbnail)
    
    def get_absolute_url(self):
        return reverse('post-recipe', kwargs={
            'pk': self.pk
        })
        
class Advertise(models.Model):
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField()
    overview = models.TextField()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-advertise', kwargs={
            'pk': self.pk
        })

    
class FeaturedPost(models.Model):
    title = models.CharField(max_length=200)
    overview = models.TextField()
    thumbnail = models.ImageField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('post-featured', kwargs={
            'pk': self.pk
        })

class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    featured = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    #content = HTMLField()
    user = models.ForeignKey(Author,on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    category = models.ForeignKey(Category, related_name='categories', on_delete=models.CASCADE)
    tags = TaggableManager()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk': self.pk
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('post-delete', kwargs={
            'pk': self.pk
        })

story/forms.py
from django import forms
from .models import Post
from django.contrib.auth import (authenticate)


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=100)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            'title', 'overview', 'thumbnail', 'category'
        )
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
    
        super(PostForm, self).__init__(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
<html lang="">

    {% include "head.html" %}

<body>
    
    {% include "nav.html" %}


    {% block content %}
    {% endblock content %}

    {% include "footer.html" %}
    {% include 'script.html' %}


    
    
</body>

</html>

templates/cat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
 
</head>
<body>  

    <div>
        <h2>{{ category.title }} category </h2>
        <h3> 
            {% for post in post_list  %}
         
            <ul>
                <li>
                        {{post.title}}
                </li>
            </ul>
                 
            {% endfor %}
        </h3>
    </div>

</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  


  <body>
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Contact Us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Contact us<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-no-pb contact-section">
      <div class="container">
        <div class="row block-9">
          <div class="col-md-6 order-md-last d-flex">

            <form method="POST" class="bg-light p-5 contact-form">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Your Name" required id="id_name">
              </div>
              <div class="form-group">
                <input type="email" name="email" class="form-control" placeholder="Your Email" required id="id_email">
              </div>
              <div class="form-group">
                <input type="text" name="subject" class="form-control" placeholder="Subject" required id="id_subject">
              </div>
              <div class="form-group">
                <textarea name="message" id="" cols="30" rows="7" class="form-control" placeholder="Message" required id="id_name"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          
          </div>

          <div class="col-md-6 d-flex">
          	<div id="map" class="bg-white">
             You could use your map right here
              <div class="mapouter"><div class="gmap_canvas">
                <iframe width="624" height="519" id="gmap_canvas" 
                src=
                "." frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
              <a href="https://www.crocothemes.net"></a></div>
              <style>.mapouter{position:relative;text-align:right;height:519px;width:624px;}.gmap_canvas {overflow:hidden;background:none!important;height:519px;width:624px;}</style></div></div>
            </div>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section contact-section">
      <div class="container">
        <div class="row d-flex contact-info">
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-map-signs"></span>
          		</div>
          		<h3 class="mb-4">Address</h3>
	            <p>198 West 21th Street, Suite 721 New York NY 10016</p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-phone2"></span>
          		</div>
          		<h3 class="mb-4">Contact Number</h3>
	            <p><a href="tel:+1234567920">+ 1235 2355 98</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-paper-plane"></span>
          		</div>
          		<h3 class="mb-4">Email Address</h3>
	            <p><a href="mailto:email@echoecho.com?subject=SweetWords">info@yoursite.com</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-globe"></span>
          		</div>
          		<h3 class="mb-4">Website</h3>
	            <p><a href="http://www.google.com">yoursite.com</a></p>
	          </div>
          </div>
        </div>
      </div>
    </section>

		
		<section class="ftco-subscribe ftco-section bg-light">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
              <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="." class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


   
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

    
  </body>

  {% endblock content %}

templates/head.html
{% load static %}

<head>
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

templates/loan.html
{% extends "base.html" %}
{% block content %}

<div class="sidebar-box ftco-animate">
    <h3 class="heading mb-4">Tag Cloud</h3>
    ghhhhh

      {% for tag in tags  %}
  
    <div class="tagcloud">
      <a href="{% url 'tagged' tag.pk %}" class="tag-cloud-link">{{tag.name}}</a>
    </div>
    {% endfor %}
  </div>

    
{% endblock content %}

templates/shit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% comment %}
    
<body>

    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Lifestyle</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Lifestyle <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>


    <section class="ftco-section">
    	<div class="container">
        <div class="row">

        	<div class="col-lg-9">
				

        		<div class="row">
						
									  
					{% for category in queryset  %}					
                        {% for post in category.post_set.all %}
                                    
        			<div class="col-md-6 col-lg-12 ftco-animate">
    						<div class="blog-entry d-lg-flex">
    							<div class="half">
			    					<a href="{{post.get_absolute_url}}" class="img d-flex align-items-end" style="background-image: url({{post.thumbnail.url}});">
			    						<div class="overlay"></div>
				    				</a>
			    				</div>
			    				<div class="text px-md-4 px-lg-5 half pt-3">
	    							<p class="meta d-flex"><span class="pr-3"><a href="{% url 'post-category' post.category.pk %}">{{post.category}}</a></span><span class="ml-auto pl-3">{{post.timestamp|date:"D d M Y"}}</span></p>
	    							<h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
	    							<p>{{post.overview|truncatechars:100}}.....</p>
	    							<p class="mb-0"><a href="{{post.get_absolute_url}}" class="btn btn-primary">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
                        </div>
                            
						{% endfor %}
                        {% endfor %}
		
                </div>



        		<div class="row mt-5">
		          <div class="col text-center">
		            <div class="block-27">
		              <ul>
		  {% include "pagination.html" %}
		              </ul>
		            </div>
		          </div>
		        </div>
        	</div>

        	<div class="col-lg-3">
        		<div class="sidebar-wrap">
	        		<div class="sidebar-box p-4 about text-center ftco-animate">
			          <h2 class="heading mb-4">About Me</h2>
			          <img src="{% static 'images/author.jpg' %}" class="img-fluid" alt="Colorlib Template">
			          <div class="text pt-4">
			          	<p>Hi! My name is <strong>Cathy Deon</strong>, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
			          </div>
	        		</div>
	        		<div class="sidebar-box p-4 ftco-animate">
	              <form action="#" class="search-form">
	                <div class="form-group">
	                  <span class="icon icon-search"></span>
	                  <input type="text" class="form-control" placeholder="Search">
	                </div>
	              </form>
	            </div>
	            <div class="sidebar-box categories text-center ftco-animate">
					<h2 class="heading mb-4">Categories</h2>
					<ul class="category-image">
						<li>
							{% for category in category.all %}
							<a href="{% url 'post-category' category.pk %}" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url({{category.thumbnail.url}});">
								<div class="text">
									<h3>{{category.title}}</h3>
								</div>
							</a>		
							{% endfor %}
						</li>
					</ul>
	        		</div>
            </div>
        	</div>
        </div>
    	</div>
    </section>

		
		<section class="ftco-subscribe ftco-section bg-light">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
              <h2 class="mb-4"><span>Subcribe to ourjjjbb Newsletter</span></h2>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  
  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>



    
  </body>

  {% endcomment %}
  <!-- <div class="sidebar-box ftco-animate">
    <ul class="categories">
        <h3 class="heading mb-4">Categories</h3>
         {% for category in queryset %}
             <li><a href="{% url 'post-category' category.pk %}">{{category}}<span>{{ category.post_set.count }}</span></a></li>
         {% endfor %}
    </ul>
</div> -->


<div class="sidebar-box ftco-animate">
    <ul class="categories">
        <h3 class="heading mb-4">Categories</h3>
         {% for category in queryset %}
             <li><a href="{% url 'post-category' category.pk %}">{{category}}<span>{{ category.posts_set.count }}</span></a></li>
             <ul>
                 {% for post in category.post_set.all %}
                     <li><a href="{% url 'post-detail' post.pk %}">{{ post }}</a></li>
                 {% endfor %}
             </ul>
         {% endfor %}
    </ul>
</div>
{% include "pagination.html" %}
{% endblock content %}

templates/single.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  

  <body>


    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Article Single</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Article Single<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 order-lg-last ftco-animate">
            <h2 class="mb-3">{{object.title}}</h2>
            <p>
              <img src="{{object.thumbnail.url}}" alt="" class="img-fluid">
            </p>
            <p>{{object.overview}}</p>
           
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">Life</a>
                <a href="#" class="tag-cloud-link">Sport</a>
                <a href="#" class="tag-cloud-link">Tech</a>
                <a href="#" class="tag-cloud-link">Travel</a>
              </div>
            </div>
            
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="{{user.author.thumbnail.url}}" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3>{{user.author.name}}</h3>
                <p>{{user.author.detail}}</p>
              </div>
            </div>


            <div class="pt-5 mt-5">
              <h3 class="mb-5">6 Comments section</h3>
              <!-- <ul class="comment-list">
                <li class="comment">
                  <div class="vcard bio">
                    <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">October 03, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>
                </li>

                <li class="comment">
                  <div class="vcard bio">
                    <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">October 03, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>

                  <ul class="children">
                    <li class="comment">
                      <div class="vcard bio">
                        <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                      </div>
                      <div class="comment-body">
                        <h3>John Doe</h3>
                        <div class="meta">October 03, 2018 at 2:21pm</div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                        <p><a href="#" class="reply">Reply</a></p>
                      </div>


                      <ul class="children">
                        <li class="comment">
                          <div class="vcard bio">
                            <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                          </div>
                          <div class="comment-body">
                            <h3>John Doe</h3>
                            <div class="meta">October 03, 2018 at 2:21pm</div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                            <p><a href="#" class="reply">Reply</a></p>
                          </div>

                            <ul class="children">
                              <li class="comment">
                                <div class="vcard bio">
                                  <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                  <h3>John Doe</h3>
                                  <div class="meta">October 03, 2018 at 2:21pm</div>
                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                  <p><a href="#" class="reply">Reply</a></p>
                                </div>
                              </li>
                            </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>

                <li class="comment">
                  <div class="vcard bio">
                    <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">October 03, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>
                </li>
              </ul> -->
              <!-- END comment-list -->
              
              <!-- <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
                <form action="#" class="p-5 bg-light">
                  <div class="form-group">
                    <label for="name">Name *</label>
                    <input type="text" class="form-control" id="name">
                  </div>
                  <div class="form-group">
                    <label for="email">Email *</label>
                    <input type="email" class="form-control" id="email">
                  </div>
                  <div class="form-group">
                    <label for="website">Website</label>
                    <input type="url" class="form-control" id="website">
                  </div>

                  <div class="form-group">
                    <label for="message">Message</label>
                    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                  </div>

                </form>
              </div> -->
            </div>

          </div> <!-- .col-md-8 -->

          <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
     
            <div class="sidebar-box ftco-animate">
              <ul class="categories">
                  <h3 class="heading mb-4">Categories</h3>
           
                   {% for category in category %}
                       <li><a href="{% url 'post-category' category.pk %}">{{category}}<span>{{ category.post_set.count }}</span></a></li>
                   {% endfor %}
              
              </ul>
          </div>
          
            
            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Recent Blog</h3>
              {% for post in recents %}
         
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({{post.thumbnail.url}});"></a>
                <div class="text">
                  <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> {{post.timestamp|date:"D d M Y"}}</a></div>
                    <div><a href="#"><span class="icon-person"></span> {{user.author.name}}</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
                 
              {% endfor %}
            </div>
      

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Tag Cloud</h3>         
              <div class="tagcloud">
                      {% for tag in tags  %}
                <a href="{% url 'tagged' tag.pk %}" class="tag-cloud-link">{{tag.name}}</a>
                        {% endfor %}
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->
		
		<section class="ftco-subscribe ftco-section bg-light">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
              <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="." class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>



    
  </body>
  {% endblock content %}